// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MikvehApi.Data;

#nullable disable

namespace MikvehApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406034248_AgregarDescripcionACita")]
    partial class AgregarDescripcionACita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MikvehApi.Models.Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaHoraCita")
                        .HasColumnType("datetime")
                        .HasColumnName("nombre_campo");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_pagar");

                    b.Property<int?>("TrabajadorId")
                        .HasColumnType("int")
                        .HasColumnName("trabajador_id");

                    b.HasKey("CitaId");

                    b.HasIndex("FechaHoraCita");

                    b.HasIndex("ClienteId", "FechaHoraCita");

                    b.HasIndex("TrabajadorId", "FechaHoraCita");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId");

                    b.HasIndex("Nombre", "Apellidos");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.DetalleCita", b =>
                {
                    b.Property<int>("DetalleCitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_cita_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCitaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("CitaId")
                        .HasColumnType("int")
                        .HasColumnName("cita_id");

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("int")
                        .HasColumnName("paquete_id");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sutotal");

                    b.HasKey("DetalleCitaId");

                    b.HasIndex("CitaId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("detalles_cita", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.DetallePaquete", b =>
                {
                    b.Property<int>("DetallePaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalle_paquete_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetallePaqueteId"));

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("int")
                        .HasColumnName("paquete_id");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("DetallePaqueteId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("detalles_paquete", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paquete_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("PaqueteId");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_base");

                    b.HasKey("ServicioId");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Trabajador", b =>
                {
                    b.Property<int>("TrabajadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trabajador_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrabajadorId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("apellidos");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("usuario");

                    b.HasKey("TrabajadorId");

                    b.HasIndex("RolId");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("trabajadores", (string)null);
                });

            modelBuilder.Entity("MikvehApi.Models.Cita", b =>
                {
                    b.HasOne("MikvehApi.Models.Cliente", "Cliente")
                        .WithMany("Citas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_citas_cliente");

                    b.HasOne("MikvehApi.Models.Trabajador", "Trabajador")
                        .WithMany("Citas")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_citas_trabajador");

                    b.Navigation("Cliente");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MikvehApi.Models.DetalleCita", b =>
                {
                    b.HasOne("MikvehApi.Models.Cita", "Cita")
                        .WithMany("DetallesCita")
                        .HasForeignKey("CitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_detalles_cita_cita");

                    b.HasOne("MikvehApi.Models.Paquete", "Paquete")
                        .WithMany("DetallesCita")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_detalles_cita_paquete");

                    b.HasOne("MikvehApi.Models.Servicio", "Servicio")
                        .WithMany("DetallesCita")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_detalles_cita_servicio");

                    b.Navigation("Cita");

                    b.Navigation("Paquete");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MikvehApi.Models.DetallePaquete", b =>
                {
                    b.HasOne("MikvehApi.Models.Paquete", "Paquete")
                        .WithMany("DetallesPaquete")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_detalles_paquete_paquete");

                    b.HasOne("MikvehApi.Models.Servicio", "Servicio")
                        .WithMany("DetallesPaquete")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_detalles_paquete_servicio");

                    b.Navigation("Paquete");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("MikvehApi.Models.Trabajador", b =>
                {
                    b.HasOne("MikvehApi.Models.Rol", "Rol")
                        .WithMany("Trabajadores")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_trabajadores_rol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MikvehApi.Models.Cita", b =>
                {
                    b.Navigation("DetallesCita");
                });

            modelBuilder.Entity("MikvehApi.Models.Cliente", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("MikvehApi.Models.Paquete", b =>
                {
                    b.Navigation("DetallesCita");

                    b.Navigation("DetallesPaquete");
                });

            modelBuilder.Entity("MikvehApi.Models.Rol", b =>
                {
                    b.Navigation("Trabajadores");
                });

            modelBuilder.Entity("MikvehApi.Models.Servicio", b =>
                {
                    b.Navigation("DetallesCita");

                    b.Navigation("DetallesPaquete");
                });

            modelBuilder.Entity("MikvehApi.Models.Trabajador", b =>
                {
                    b.Navigation("Citas");
                });
#pragma warning restore 612, 618
        }
    }
}
